# Generated by Django 4.2.7 on 2024-08-19 08:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Nom de la catégorie', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default="Contenu de l'article", null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('disabled', 'Désactivé'), ('rejected', 'Rejeté'), ('in_review', 'En attente'), ('published', 'Publié')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(blank=True, default="Sous-titre de l'article", null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default="Nom de l'article", max_length=100),
        ),
    ]
